/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const HealthPackageId = IDL.Text;
export const HealthPackage = IDL.Record({
  'id' : HealthPackageId,
  'turnaroundTime' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPopular' : IDL.Bool,
  'sampleType' : IDL.Text,
  'imageUrl' : IDL.Text,
  'includedTests' : IDL.Vec(IDL.Text),
  'marketPrice' : IDL.Nat,
  'discountedPrice' : IDL.Nat,
  'testParameters' : IDL.Vec(IDL.Text),
});
export const LabTestId = IDL.Text;
export const LabTest = IDL.Record({
  'id' : LabTestId,
  'turnaroundTime' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sampleType' : IDL.Text,
  'imageUrl' : IDL.Text,
  'marketPrice' : IDL.Nat,
  'discountedPrice' : IDL.Nat,
  'testParameters' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'manufacturer' : IDL.Text,
  'name' : IDL.Text,
  'ratings' : IDL.Vec(IDL.Nat),
  'description' : IDL.Text,
  'stockCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'requiresPrescription' : IDL.Bool,
  'price' : IDL.Nat,
  'discountedPrice' : IDL.Opt(IDL.Nat),
});
export const OrderItem = IDL.Record({
  'quantity' : IDL.Nat,
  'product' : Product,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const OrderId = IDL.Text;
export const ArticleId = IDL.Text;
export const Article = IDL.Record({
  'id' : ArticleId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
});
export const UserId = IDL.Text;
export const LabTestBooking = IDL.Record({
  'id' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Time,
  'appointmentTime' : Time,
  'labTestId' : LabTestId,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'userId' : UserId,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const PrescriptionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Prescription = IDL.Record({
  'id' : IDL.Text,
  'status' : PrescriptionStatus,
  'userId' : UserId,
  'orderId' : OrderId,
  'image' : ExternalBlob,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'addresses' : IDL.Vec(Address),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHealthPackage' : IDL.Func([HealthPackage], [HealthPackageId], []),
  'addLabTest' : IDL.Func([LabTest], [LabTestId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookLabTest' : IDL.Func([LabTestId, Time], [IDL.Text], []),
  'createOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Nat, Address, IDL.Bool],
      [OrderId],
      [],
    ),
  'deleteHealthPackage' : IDL.Func([HealthPackageId], [], []),
  'deleteLabTest' : IDL.Func([LabTestId], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(LabTestBooking)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllLabTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getArticleById' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthPackage' : IDL.Func(
      [HealthPackageId],
      [IDL.Opt(HealthPackage)],
      ['query'],
    ),
  'getHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
  'getLabTestById' : IDL.Func([LabTestId], [IDL.Opt(LabTest)], ['query']),
  'getMyLabTestBookings' : IDL.Func([], [IDL.Vec(LabTestBooking)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getOrdersByUser' : IDL.Func([UserId], [IDL.Vec(Order)], ['query']),
  'getPopularHealthPackages' : IDL.Func(
      [],
      [IDL.Vec(HealthPackage)],
      ['query'],
    ),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchHealthPackages' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat))],
      [IDL.Vec(HealthPackage)],
      ['query'],
    ),
  'searchProducts' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'seedData' : IDL.Func([], [], []),
  'updateHealthPackage' : IDL.Func([HealthPackageId, HealthPackage], [], []),
  'updateLabTest' : IDL.Func([LabTestId, LabTest], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updatePrescriptionStatus' : IDL.Func([IDL.Text, PrescriptionStatus], [], []),
  'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  'uploadPrescription' : IDL.Func([OrderId, ExternalBlob], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const HealthPackageId = IDL.Text;
  const HealthPackage = IDL.Record({
    'id' : HealthPackageId,
    'turnaroundTime' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPopular' : IDL.Bool,
    'sampleType' : IDL.Text,
    'imageUrl' : IDL.Text,
    'includedTests' : IDL.Vec(IDL.Text),
    'marketPrice' : IDL.Nat,
    'discountedPrice' : IDL.Nat,
    'testParameters' : IDL.Vec(IDL.Text),
  });
  const LabTestId = IDL.Text;
  const LabTest = IDL.Record({
    'id' : LabTestId,
    'turnaroundTime' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sampleType' : IDL.Text,
    'imageUrl' : IDL.Text,
    'marketPrice' : IDL.Nat,
    'discountedPrice' : IDL.Nat,
    'testParameters' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'manufacturer' : IDL.Text,
    'name' : IDL.Text,
    'ratings' : IDL.Vec(IDL.Nat),
    'description' : IDL.Text,
    'stockCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'requiresPrescription' : IDL.Bool,
    'price' : IDL.Nat,
    'discountedPrice' : IDL.Opt(IDL.Nat),
  });
  const OrderItem = IDL.Record({ 'quantity' : IDL.Nat, 'product' : Product });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const OrderId = IDL.Text;
  const ArticleId = IDL.Text;
  const Article = IDL.Record({
    'id' : ArticleId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  const UserId = IDL.Text;
  const LabTestBooking = IDL.Record({
    'id' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Time,
    'appointmentTime' : Time,
    'labTestId' : LabTestId,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'deliveryAddress' : Address,
    'userId' : UserId,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const PrescriptionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Prescription = IDL.Record({
    'id' : IDL.Text,
    'status' : PrescriptionStatus,
    'userId' : UserId,
    'orderId' : OrderId,
    'image' : ExternalBlob,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'addresses' : IDL.Vec(Address),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHealthPackage' : IDL.Func([HealthPackage], [HealthPackageId], []),
    'addLabTest' : IDL.Func([LabTest], [LabTestId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookLabTest' : IDL.Func([LabTestId, Time], [IDL.Text], []),
    'createOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Nat, Address, IDL.Bool],
        [OrderId],
        [],
      ),
    'deleteHealthPackage' : IDL.Func([HealthPackageId], [], []),
    'deleteLabTest' : IDL.Func([LabTestId], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(LabTestBooking)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllLabTests' : IDL.Func([], [IDL.Vec(LabTest)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getArticleById' : IDL.Func([ArticleId], [IDL.Opt(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthPackage' : IDL.Func(
        [HealthPackageId],
        [IDL.Opt(HealthPackage)],
        ['query'],
      ),
    'getHealthPackages' : IDL.Func([], [IDL.Vec(HealthPackage)], ['query']),
    'getLabTestById' : IDL.Func([LabTestId], [IDL.Opt(LabTest)], ['query']),
    'getMyLabTestBookings' : IDL.Func([], [IDL.Vec(LabTestBooking)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getOrdersByUser' : IDL.Func([UserId], [IDL.Vec(Order)], ['query']),
    'getPopularHealthPackages' : IDL.Func(
        [],
        [IDL.Vec(HealthPackage)],
        ['query'],
      ),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchHealthPackages' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat))],
        [IDL.Vec(HealthPackage)],
        ['query'],
      ),
    'searchProducts' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'seedData' : IDL.Func([], [], []),
    'updateHealthPackage' : IDL.Func([HealthPackageId, HealthPackage], [], []),
    'updateLabTest' : IDL.Func([LabTestId, LabTest], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updatePrescriptionStatus' : IDL.Func(
        [IDL.Text, PrescriptionStatus],
        [],
        [],
      ),
    'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
    'uploadPrescription' : IDL.Func([OrderId, ExternalBlob], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };