/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface Article {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'date' : Time,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
}
export type ArticleId = string;
export type ExternalBlob = Uint8Array;
export interface HealthPackage {
  'id' : HealthPackageId,
  'turnaroundTime' : string,
  'name' : string,
  'description' : string,
  'isPopular' : boolean,
  'sampleType' : string,
  'imageUrl' : string,
  'includedTests' : Array<string>,
  'marketPrice' : bigint,
  'discountedPrice' : bigint,
  'testParameters' : Array<string>,
}
export type HealthPackageId = string;
export interface LabTest {
  'id' : LabTestId,
  'turnaroundTime' : string,
  'name' : string,
  'description' : string,
  'sampleType' : string,
  'imageUrl' : string,
  'marketPrice' : bigint,
  'discountedPrice' : bigint,
  'testParameters' : Array<string>,
}
export interface LabTestBooking {
  'id' : string,
  'userId' : UserId,
  'createdAt' : Time,
  'appointmentTime' : Time,
  'labTestId' : LabTestId,
}
export type LabTestId = string;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'deliveryAddress' : Address,
  'userId' : UserId,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export type OrderId = string;
export interface OrderItem { 'quantity' : bigint, 'product' : Product }
export type OrderStatus = { 'shipped' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Prescription {
  'id' : string,
  'status' : PrescriptionStatus,
  'userId' : UserId,
  'orderId' : OrderId,
  'image' : ExternalBlob,
  'uploadedAt' : Time,
}
export type PrescriptionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Product {
  'id' : ProductId,
  'manufacturer' : string,
  'name' : string,
  'ratings' : Array<bigint>,
  'description' : string,
  'stockCount' : bigint,
  'imageUrl' : string,
  'category' : string,
  'requiresPrescription' : boolean,
  'price' : bigint,
  'discountedPrice' : [] | [bigint],
}
export type ProductId = string;
export type Time = bigint;
export type UserId = string;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'addresses' : Array<Address>,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHealthPackage' : ActorMethod<[HealthPackage], HealthPackageId>,
  'addLabTest' : ActorMethod<[LabTest], LabTestId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookLabTest' : ActorMethod<[LabTestId, Time], string>,
  'createOrder' : ActorMethod<
    [Array<OrderItem>, bigint, Address, boolean],
    OrderId
  >,
  'deleteHealthPackage' : ActorMethod<[HealthPackageId], undefined>,
  'deleteLabTest' : ActorMethod<[LabTestId], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllBookings' : ActorMethod<[], Array<LabTestBooking>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllLabTests' : ActorMethod<[], Array<LabTest>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getArticleById' : ActorMethod<[ArticleId], [] | [Article]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHealthPackage' : ActorMethod<[HealthPackageId], [] | [HealthPackage]>,
  'getHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'getLabTestById' : ActorMethod<[LabTestId], [] | [LabTest]>,
  'getMyLabTestBookings' : ActorMethod<[], Array<LabTestBooking>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getOrdersByUser' : ActorMethod<[UserId], Array<Order>>,
  'getPopularHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchHealthPackages' : ActorMethod<
    [string, [] | [[bigint, bigint]]],
    Array<HealthPackage>
  >,
  'searchProducts' : ActorMethod<
    [
      string,
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [string],
      [] | [boolean],
      [] | [string],
    ],
    Array<Product>
  >,
  'seedData' : ActorMethod<[], undefined>,
  'updateHealthPackage' : ActorMethod<
    [HealthPackageId, HealthPackage],
    undefined
  >,
  'updateLabTest' : ActorMethod<[LabTestId, LabTest], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updatePrescriptionStatus' : ActorMethod<
    [string, PrescriptionStatus],
    undefined
  >,
  'uploadImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'uploadPrescription' : ActorMethod<[OrderId, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];